### ISSUE TITLE
Named Lizardmen Characters

### ISSUE THREAD

**Issue by tawilkinson** [Ergofarg/Warhammer-Fantasy-6th-edition#19]
The Lizardmen Catalog seems to be missing both Lord Kroak and Krok-Gar. I have the 2003 army book and I am happy to help add them if that helps using the Battlescribe data editor.

I've not tinkered with this before so how do you handle a choice using up multiple slots (e.g. Lord, Hero & Rare for Kroak)?

**Comment by tawilkinson** [comment]
I've worked out how to do the above. I think I have a working version of Kroak ready. Working on Kroq-Gar now.

**Comment by Ergofarg** [comment]
Great now I would have over written this. Unless I am told in the group messenger chat I am not going to know
