### ISSUE TITLE
Army selection complains about Rare choices

### ISSUE THREAD

**Issue by tawilkinson** [Ergofarg/Warhammer-Fantasy-6th-edition#21]
A 2,000+pt force complains about having too many Rare choices when there is only one Rare choice. It should allow up to 2

**Comment by tawilkinson** [comment]
The issue is if the points limit is set to -1. Should be easy to fix this so it scales

**Comment by Ergofarg** [comment]
Or put a note saying you must specify a limit as unlimited does not work in conditions set.

**Comment by tawilkinson** [comment]
I think there is a benefit to having an unlimited option if you want to track what your complete collection contains perhaps? I do a similar thing with my Necrons but then again I have so many HQ choices it always complains at me anyway 🤣
