### ISSUE TITLE
README Updates 

### ISSUE THREAD

**Issue by tawilkinson** [Ergofarg/Warhammer-Fantasy-6th-edition#23]
Now that #22 has been merged this repo should auto generate indexes as per discussion in that PR. To get this setup so users know what to do we need to:

1. Make a GitHub Release of the current version (this will kick off the workflow)
2. Generate screenshots for iOS, Android and Desktop showing how to add via this new method (which requires the release to be done so we can show it working)
3. Add sections to the README with these screenshots

**Comment by Bercelak** [comment]
Sounds good. Just created the release and I can work on documentation for the desktop and Android client (if I get time this evening). I don't have an iOS device, however, so someone else will have to assist on that front.

**Comment by tawilkinson** [comment]
I have made screenshots for Android. I have an iPad which I assume has the same interface as an iPhone and can sort that this weekend.

**Comment by Bercelak** [comment]
No problem!

**Comment by Bercelak** [comment]
Thanks for all the work!
