### ISSUE TITLE
Empire Roster-Detachments equipment issue- spearmen+free company

### ISSUE THREAD

**Issue by vampirerosterupdate** [Ergofarg/Warhammer-Fantasy-6th-edition#24]
Greetings, and thanks for this great resource.

1.Free Company detachments bought from parent units within the list shouldn't come with light armour -it being an optional equip upgrade

2. Spearmen detachments incorrectly come with the option of purchasing a banner.

**Comment by Ergofarg** [comment]
The Free company detachment do not come with Light armour. The light armour refers to the parent unit. Corrected the Spearmen detachments. Thanks for your vigilance.

**Comment by Bercelak** [comment]
I'm going to close this.
