### ISSUE TITLE
Roster issues with daemonic characters and generals

### ISSUE THREAD

**Issue by HoCplayer** [Ergofarg/Warhammer-Fantasy-6th-edition#28]
The exalted daemon and demon prince general options both appear to be missing the "Master of mortals" daemonic power.

In addition, when a sorceress of chaos is selected as a general with an exalted daemon in the roster as well, the roster gets a validation error stating "sorceress of chaos has 1 too many selection of general (maximum 0)", even though characters with identical leadership should grant a choice of who can be general between them.

Characters in chariots with a mark of chaos also need the chariot to have a mark matching theirs, but the character mount upgrade for chariots only applies the base undivided chariot and cost regardless of what mark the character has.

**Comment by Ergofarg** [comment]
The Master of Mortals is an easy fix. 
I will take your word that you can pick the general. I have written this as the Exalted Daemon must be general, I may have misentrepted some rules.
Chariots will need time to think this one over.

**Comment by Ergofarg** [comment]
> In addition, when a sorceress of chaos is selected as a general with an exalted daemon in the roster as well, the roster gets a validation error stating "sorceress of chaos has 1 too many selection of general (maximum 0)", even though characters with identical leadership should grant a choice of who can be general between them.
> 
Got it . Page 59 Hordes of chaos, just below the bit about BSB, states Sorcerer cannot be general if another character is present.
