### ISSUE TITLE
Add Chaos Dwarfs 

### ISSUE THREAD

**Issue by shareif** [Ergofarg/Warhammer-Fantasy-6th-edition#29]
Chaos Dwarfs are playable as per Ravening Hordes. Current catalogue do not include Chaos Dwarfs army.

**Comment by shareif** [comment]
I've created the CD file just do not have rights to commit it :)

**Comment by Bercelak** [comment]
Do you know how to do a pull request? You can request for a merge through that method.

**Comment by Ergofarg** [comment]
Send it to me first.

**Comment by shareif** [comment]
> Do you know how to do a pull request? You can request for a merge through that method.

I can, just I do not see the option to do it in github. Maybe I do not have permissions?

**Comment by Ergofarg** [comment]
I have no clue what I am doing in github.

**Comment by Bercelak** [comment]
@shareif: in order to do a pull request, you will need to fork this repo, and then commit the work that you have done. Then you will be able to make a pull request. No extra permissions necessary.

**Comment by shareif** [comment]
@Bercelak Done! Thanks for the hints!

**Comment by Bercelak** [comment]
Merged the pull request closing.
