### ISSUE TITLE
Chaos Point Cost

### ISSUE THREAD

**Issue by Kloerb** [Ergofarg/Warhammer-Fantasy-6th-edition#31]
I compared some of the point costs with my own 6th edition battlescribe and checked with the army book whenever there was a conflict. I hope it's alright to post it here.

- A lot of units with Chaos Armour cost 10 points too much because the armour itself has a cost of 10 points attached to it. I confirmed the following: Chosen Upgrade (Warriors and Knights), Aspiring Champions, Exalted Champions, Chaos Lords (Armour is also not equipped by default)
- Marauder Horsemen cost 5 points/pop, should be 13
- Minotaur Mark of Slaanesh costs 25 points, should be 20
- Mount options for Chaos Lords: Juggernaught and Steed of Slaanesh are missing
- Chaos Runesword: costs 75 points, should be 70
- Regarding the point cost of gifts the greater demons carry, I always read them as being baked into their base cost and thus not costing additional points. I wasn't able to find any FAQ on the topic however so if you conciously decided to make them cost points I won't argue with that.

**Comment by Bercelak** [comment]
Thank you for finding those inconsistencies! We will (hopefully) be able to address those.
