### ISSUE TITLE
Error in Tomb Kings chariot profile

### ISSUE THREAD

**Issue by DanBringa** [Ergofarg/Warhammer-Fantasy-6th-edition#38]
There is 2 errors in the Tomb Kings chariot profile.
The skeleton crew has Ws3, but it's listed as Ws2.
They are also Ld7, but listed as Ld3.

Thanks.

**Comment by Ergofarg** [comment]
Thanks for pointing these out

**Comment by Ergofarg** [comment]
The files have been altered and fixed.
