### ISSUE TITLE
Extra Dark elf magic items.

### ISSUE THREAD

**Issue by DanBringa** [Ergofarg/Warhammer-Fantasy-6th-edition#46]
Howdy doodily do?

Could the magic items from the storm of chaos cult of slaanesh be added to the dark elf army list? As they are usable by normal Dark Elves.

Thanks

Dan

**Comment by Ergofarg** [comment]
Er I thought they were. What is the latest Dark elf build you have?

**Comment by DanBringa** [comment]
Says v4 in mine. Has battlescribe not updated again?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Bercelak** [comment]
It's possible they were added since the last time I created a release. I'll go ahead and create one now.

**Comment by Ergofarg** [comment]
Did you goto the Facebook group for the download or pull the file from here? It should be V5. Could be that I have not updated github. Pull the file and see if it is v5

**Comment by Bercelak** [comment]
@Ergofarg It's V5 in the repo, so it is the most up-to-date.

**Comment by DanBringa** [comment]
All sorted, it was an issue with battlescribe not updating properly. All sorted now.

**Comment by Bercelak** [comment]
Great!
