### ISSUE TITLE
Could we help merge this into https://github.com/BSData/whfb so it appears in New Recruit?

### ISSUE THREAD

**Issue by gommo** [Ergofarg/Warhammer-Fantasy-6th-edition#47]
Has there been previous discussion to do this? 
I'm happy to help as well.

As far as I know, this would have to happen in order for Battle Scribe and New Recruit etc.. to show this repo by default right? They don't seem to want to create new repositories for different editions of games

**Comment by Ergofarg** [comment]
You need to explain some things first as I have no idea what you are talking about.

**Comment by gommo** [comment]
:) No worries. And I may be wrong with below but..

As I understand, for 6th edition to appear in Battlescribe and New Recruit [(newrecurit.eu)], it must be part of an existing catalog. And, as there is already a Warhammer Fantasy catalog, the owners of that GitHub repo would want the version added to that. I believe you had already requested a separate repo a few years back and the request was closed because of this.  (See https://github.com/BSData/catalogue-development/issues/147)

So, I guess what I'm asking is should we just add the files from this repo into a Pull Request in this GitHub repo and see if it can be merged in?  This repo -> https://github.com/BSData/whfb

That way people don't have to manually add this repo to Battle Scribe (and they also get to use it in New Recruit, as there is no way to add arbitrary battlescribe game systems that aren't in the main repos)

I guess I can always try the above, but I wanted to check with you first.

Thanks mate

**Comment by gommo** [comment]
i.e. Something like this - https://github.com/gommo/whfb/tree/6thedition

**Comment by Ergofarg** [comment]
No i dont want anything to do with those losers. Fuck em and their incomplete listings.

**Comment by gommo** [comment]
All good, I won't get in the middle of that then lol

Just was trying to remove any barriers for people getting into 6th. I've answered a bunch of questions about getting that bsi file into BS for mobile that's all.

I might see how the whfb 7th ed files are and if easy to backport some of them to 6th

**Comment by gommo** [comment]
close
