### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by Cylindryk** [Ergofarg/Warhammer-Fantasy-6th-edition#48]
Hey.
It is not really an issue, but is there a possibility to add these files to common BSData repositories, so it could be downloaded to New Recruit?
NR is kinda superior in most things compared to BS, support included. :)

Also, any way to contact you by other means, like FB or Discord?

**Comment by Bercelak** [comment]
Sorry for the very late reply, but we will not be adding this repo to the other BSData repositories. While New Recruit is a cool tool, it is beyond the scope of our effort here.

And if you haven't found it yet, there's a link to Facebook in the README to connect with us.
