### ISSUE TITLE
Complete the Wood Elf catalog

### ISSUE THREAD

**Issue by Bercelak** [Ergofarg/Warhammer-Fantasy-6th-edition#9]
Finish adding all the units, heroes, etc for the Wood Elf catalog

**Comment by Bercelak** [comment]
The catalog is complete, and in the interest of not letting this languish I am closing this one.

**Comment by Ergofarg** [comment]
This is far from finished

**Comment by Bercelak** [comment]
Oops, thanks for catching that.

**Comment by matprzybyla** [comment]
Are wood elves roosters coming into catalog? Currently there is only an empty one in latest version.

**Comment by Bercelak** [comment]
@matprzybyla 
We move slowly, since this is a hobby project, but the plan is to include the Wood Elves. You can always contribute if you would like to see that happen sooner!

**Comment by Ergofarg** [comment]
If you or anyone can write out the wood elf magic items in doc format or text format, that would greatly help me. On every entry their is a paragraph of fluff and then the paragraph of what the magic item actually does. I just need the latter, not worried about the fluff.

**Comment by matprzybyla** [comment]
Will be happy to help. Have the 6th ed army book so will prepare the files somewhere next week.

**Comment by matprzybyla** [comment]
[BattleScribe WE items.docx](https://github.com/Ergofarg/Warhammer-Fantasy-6th-edition/files/9284807/BattleScribe.WE.items.docx)

Hi @Ergofarg - uploeded a file with Wood Elf magic items from the book. Added Spites also - was not sure it this may come in handy.
Took me a while longer to make it but it there - hope format is ok and you can use it? Please let me know if needs some adjustments

**Comment by Ergofarg** [comment]
Thanks @matprzybyla that will be handy. Been busy at work recently but I will try yo get these in soon.

**Comment by matprzybyla** [comment]
Hi @Ergofarg - just noticed that Hail of Doom Arrow costs 35 point in battlescribe and just 30 in army book.
No sure where to report it to be corrected :)

**Comment by Ergofarg** [comment]
Will be fixed on next update unless you use the files on here, in which case you will instantly have the update by using these files

**Comment by Bercelak** [comment]
Thank you for the reminder to create a new release!
